name: Code Review Bot

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get code diff
        id: diff
        run: |
          git fetch origin main # Fetch only the latest commit from main
          git diff origin/main...HEAD > diff.patch
          echo "diff_file=diff.patch" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run code review with DeepSeek
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: |
          export DIFF=$(cat diff.patch | head -c 6000)
          python .github/scripts/review.py
