name: Code Review Bot

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get code diff
        id: diff
        run: |
          git fetch origin main --unshallow  # Fetch the full history of the main branch
          git diff origin/main...HEAD > diff.patch
          echo "diff_file=diff.patch" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run code review with DeepSeek
        id: review
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
        run: |
          export DIFF=$(cat diff.patch | head -c 6000)
          python .github/scripts/review.py > review_result.txt
          cat review_result.txt

      - name: Set review output
        id: set_output
        run: |
          echo "review_text<<EOF" >> $GITHUB_OUTPUT
          cat review_result.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.set_output.outputs.review_text }}
          reactions: '+1'
